Language <-
{
        "English":
	{

                /* scripts/Classes/playerevent.nut and scripts/Classes/player.nut */
                CantSpawnNotReq = "[#e60000]Your need to register your account."
                CantSpawnNotLog = "[#e60000]You need to login into your account."
        	    AccAutoLogged = "[#00cc00]You have been auto logged-in."
                RegScs = "[#00cc00]You have been registered successfully!"
                LogScs =  "[#00cc00]You have been logged in successfully!"
                RegAlreadyRegistered = "[#e68a00]This account is already registered!"
                LoginXPassword = "[#e68a00]Wrong password!"
                NotReg = "[#e68a00]This account is not registered."
                AccJoined = "[#ffffff][ %s ] has joined the server from [ %s ]."
                AccJoined1 = "[#ffffff][ %s ] joined the server for the first time from [ %s ]."
                PartReasonLeft = "[#ffffff][ %s ] disconnected from the server."
                PartReasonTimeout = "[#ffffff][ %s ] lost connection to the server."
                PartReasonKicked = "[#ffffff][ %s ] has been kicked from the server."
                PartReasonCrash = "[#ffffff][ %s ] game crashed."
                TeamChat = "[Team Chat] %s[#ffffff]: %s"
                Chat = "%s[#ffffff]: %s"
				asay = "[#ffea00]%s[#ffffff]:[#ff0000] %s"
                CantTalkMuted = "[#e60000]You cannot chat because you are muted."
                ChatModeSwitch = "[#00e64d]Chat mode has been switched to [ %s ]"
                onPlayerPMSender = "[#ffff00]You have sent [ %s ][%d] private message [ %s ]"
                onPlayerPMReceiver = "[#ffff00][ %s ][%d] has sent private message to you [ %s ]"
                TeamESPSwitchDis = "[#00e64d]You disabled show teammate position."
                TeamESPSwitchEn = "[#00e64d]You enabled show teammate position."
                TeamShooting = "[#00e699]The vehicle is being shot at by [ %s ]."
                LoginAlert = "[#e60000]This account already registered, please login with /login"
                WarningPing1 = "[#e60000]You cannot spawn because your ping is higher than [ %d ]"
                FPSLimit1 = "[#e60000]You cannot spawn because your fps is lower than [ %d ]"
                PickupCantUseEnemyPickup = "[#e68a00]You cannot use enemy resource."
                PickupGetHit = "[#e60000]You need to wait [ %s ] because you recently get hitted by other player."
                onPlayerPM = "[#ffff99]Private message: [%s] to [%s]: [ %s ]"
                onPlayerTeamChat = "[#ffff99]Team chat: [%s][ %s ]: [ %s ]"
                CantPMTargetDisallowPM = "[#e68a00]Target player disabled private message."
                AccJoined2 = "[#ffffff][ %s ] has joined the server."
                ReadOnlyAlert = "[#e68a00]Warning! This server is on read only mode, your progress wont be saved."
                AccJoined4 = "[#ffff99][ %s ] has joined the server from [ %s ]."
                PickupInCD = "[#e68a00]You need to wait [ %s ] before you can pick this."
                CantPMTargetIgnored = "[#e68a00]You cannot send private message to target player because he/she already ignored you."
                CantPMIgoreTarget = "[#e68a00]You cannot send private message to target player which you ignore."
                CantPMNotLogged = "[#e68a00]You must logged to use this command."
                onPlayerPMReceiverA = "[#ff0000]Admin [ %s ][%d] has sent private message to you [ %s ]"
                CantTalkChatDisabled = "[#e68a00]Public chat has been disabled by administrator."
                AllowNonAdminSpawnAsRef = "[#e68a00]You must be administrator to spawn as referee."
                CantTalkChatDisabled2 = "[#e68a00]You cannot talk in public chat because you disabled public chat."
                ShowComments = "[#ffff99][ %s ] admin comments [ %s ]."
                JoinMessage2 = "[#ffff99][ %s(%s) ] joining the server."
                
                /* scripts/Classes/gameplay.nut */
                Replaybase = "Replaying base in %d seconds."
                PrepRound = "[#00e699]Preparing round. Base [ %s ] Defender [ %s ]"
                BaseInfo = "[#00e699]Author [ %s ] Steal record [ %s (%s) ]"
                RoundStart = "[#00e699]Round started. Base [ %s ] Defender [ %s ]"
                TookSet = "You took pack %s."
                AlreadyTookSameSet = "You have already taken this pack." 
				SetLimitReached = "Too many people are using this pack, please pick another one."
                ChangePackNextSpawn = "Your pack will change on next spawn."
                RoundWinMoreScore = "[#00e699][ %s ] have successfully defended the vehicle."
                RoundWinVehicleDelivered = "[#00e699][ %s ] have stolen the vehicle."
                RoundEndNoPlayer = "[#00e699]Round has been ended because there were not enough players."
                MVPDriver = "[#00e699]MVP: [ %s ] for delivering the target vehicle."
                MVPKiller = "[#00e699]MVP: [ %s ] for making top kills."
                MVPMakeNewRecord = "[#00e699]MVP: [ %s ] for making new base record."
                AttEnterVehicle = "%s has entered the target vehicle."
                AttExitVehicle = "%s ejected from the target vehicle, respawning vehicle in 10 seconds."
                TargetVehicleRespawn = "Target vehicle respawned."
                DeliveringNotice = "Stay in the sphere for %d second(s) to deliver the vehicle"
                DeliverFailedODriverLeft = "%s failed to deliver the target vehicle. Respawning vehicle."
                TakeDefVehicleNotice = "Rob %s's Vehicle and deliver it here."
                DeliverFailVehicleOutCP = "Failed to deliver the target vehicle, vehicle not at checkpoint."
                TargetVehicleXplode = "Target vehicle destroyed. Respawning vehicle in 10 seconds.."
                TeamSurrender = "[#00e699][ %s ] has forfeited this round."
                StopVoteBcsNoPlayer = "Voting session has been stopped due to no players in-game."
                StopVoteAdmin = "Voting has been ended by admin."
				StopRVoteAdmin = "Replay base has been stopped by admin."
                StopPrepBcsNoPlayer = "Round initializing process has been aborted due to no players in-game."
                KillReason2 = "%s [#d5d6d7]+ %s [#d5d6d7]killed %s [#d5d6d7][%s] [%s] [%.4fm] [%d Ping] [%.2f FPS]"
				KillReason = "%s [#d5d6d7]killed %s [#d5d6d7][%s] [%s] [%.4fm] [%d Ping] [%.2f FPS]"
                KillReasonRed = "[#3366ff]%s [#d5d6d7]killed [#ff3300]%s [#d5d6d7][%s] [%s] [%.4fm] [%d Ping] [%.2f FPS]"
                KillReasonBlue = "[#ff3300]%s [#d5d6d7]killed [#3366ff]%s [#d5d6d7][%s] [%s] [%.4fm] [%d Ping] [%.2f FPS]"			
                DeathReasonSuicide = "%s [#8c8c8c]commited suicide."
                DeathReasonCarCrash = "%s [#8c8c8c]died in a car crash."
                DeathReasonBurn = "%s [#8c8c8c]burnt to death."
                DeathReasonChoke = "%s [#8c8c8c]choked to death."
                DeathReasonDrown = "%s [#8c8c8c]drowned."
                DeathReasonExplode = "%s [#8c8c8c]exploded."
                DeathReasonFell = "%s [#8c8c8c]fell to death."
                DeathReason = "%s [#8c8c8c]died."
                RoundStats = "[#e6e600]Your round stats: "
                RoundStats1 = "[#e6e600]Kills [ %d ] Deaths [ %d ] Highest spree [ %d ]"
                AccError = "[#e60000]An error occured while loading your account."
                TargetExeededLimitRespawnVehicle = "Target vehicle has been respawned for going out of bounds!"
                KillingSpree = "[#00e699][ %s ] is on a killing spree of [ %d ]!"
				EndKillingSpree = "[#00e699][ %s ] killing spree of [ %d ] has been ended by [ %s ]!"
				EndKillingSpreeOwn = "[#00e699][ %s ] has ended their own killing spree!"
                MVPMakeNewRecordDriver = "[#00e699]MVP: [ %s ] for breaking RTV record with [ %s ] (Past Record: %s)"
                MVPMakeNewRecordDriver1 = "[#00e699]MVP: [ %s ] for making new RTV record with [ %s ]"
                VoteBaseNotice = "Use [1/6] Keys to vote for bases that are listed on GUI."
                WarningFPS = "[#e68a00]Your average fps is lower than [ %d ]. Fix it or you will be removed from round. Warning [%d/4]"
                FPSRemoved = "[#ffc266][ %s ] has been removed from the round due to low fps. [%f/%d]"
                WarningPing = "[#e68a00]Your average ping is higher than [ %d ]. Fix it or you will be removed from round. Warning [%d/4]"
                PingRemoved = "[#ffc266][ %s ] has been removed from the round due to high ping. [%d/%d]"
                CantTakeRPG = "You cannot take this pack because %s has already taken this pack."
                DeliverFailedVehicleDamage = "%s failed to deliver the target vehicle because vehicle was damaged."
                DamageVehFirst = "[#e6e600][ %s ] is did first damage on the vehicle!"
                TargetVehOnFire = "[#e6e600]Target Vehicle is on fire!"
                VoteCastAll = "[#e68a00][ %s ] has voted for base [ %s ]."
                AutoSpawnDisable = "[#00e64d]Autorespawn has been disabled."
                AutoSpawnEnable = "[#00e64d]Autorespawn has been enabled."
                SpreeBonus = "[#e6e600]You recieved +15 HP and restored ammo as spree reward."
                PackChangeSameRPG = "[#e68a00]Your pack has been changed to pack 1 because [ %s ] already take set 4."
                DisarmRPGBan = "[#e68a00]Your pack have been changed to set 1 because you are banned from using Rocket Launcher."
                CantTakeRPGBanned = "You cannot take this set because you are banned from using this set."
                GetRoundStatsOutput = "[#00e6e6]You can view the stats of this round on %s"
                TeamSurrender1 = "[#00e699][ %s ] has surrendered."
                SurrenderS = "Type /surrender to surrender during round."
                JitterRemoved = "[#ffc266][ %s ] has been removed from the round due to high jitter. [%d/%d]"
                WarningJitter = "[#e68a00]Your jitter is higher than [ %d ]. Fix it or you will be removed from round. Warning [%d/4]"
                JittlerWarning = "[#ffff99]Warning! [ %s ] jitter exceeded limit! [%d/%d] Warning [%d/4]"
                RPGCloseLimit = "[#ffff99]Warning! [ %s ] RPG close combat! [ %.4fm ]"
                DestroyMine = "[#e6e600]You destroyed enemy mine."
                FPSWarning = "[#ffff99]Warning! [ %s ] average FPS below limit! [%d/%d] Warning [%d/4]"
                PingWarning = "[#ffff99]Warning! [ %s ] average ping exceeded limit! [%d/%d] Warning [%d/4]"
                KillReasonT = "%s [#d5d6d7]team killed %s [#d5d6d7][%s] [%s] [%.4fm]"
                AFKRemoved =  "[#ffc266][ %s ] has been removed from the round due to being afk."
                CantChangePackTooFar = "[#e68a00]You cannot change pack because you are too far away from your own spawn."
                AFKCheckpoint = "[#ffff99][ %s ] alt tabbed while capturing checkpoint."
                AnnScore = "[#00e64d]Score: [ %s ] [%d] - [%d] [ %s ]"
                PingRemoved2 = "[#ffc266][ %s ] has been kicked from the server due to high ping. [%d/%d]"
                FPSRemoved2 = "[#ffc266][ %s ] has been kicked from the server due to low fps. [%f/%d]"
                JitterRemoved2 = "[#ffc266][ %s ] kicked from the server due to high jitter. [%d/%d]"
                PackSelectAdmin = "[#ffff99][%s] [ %s ] has took pack [ %d ] [%d/%d]"
                PackSelectTeam = "[Team Chat] %s[#ffffff]: [#00ffff]I took pack [ %d ]."
                ShowTaunt2 = "%s: %s"

                /* scripts/Classes/functions.nut */
                KillBonus = "[#e6e600]You got [ +%d ] HP as kill bonus."
                SpawnBanAlert = "[#e60000]You have been spawn banned, make an appeal to the respective admin."


                /* scripts/Classes/playeruid.nut */
                Kickban = "[#e60000]You have been banned by admin [ %s ] for [ %s ] on [ %s ]"
                UnbanForum = "[#e60000]Post unban appeal on [ %s ]"
                KickbanTimered = "[#e60000]Your ban will expire in [ %s ]"
				DisallowMultiClient = "[#e60000]Multi-client is not allowed."
                DisallowMultiClientTime = "[#e60000]Multi-client is not allowed, kicking in %d..."
                AccountNotActivated = "[#00e6e6]We have revised our server policies: it seems your account is registered with us but not activated yet. You can either wait or poke a admin at our forum or discord for activation."
                AccountNotReg = "[#00e6e6]We have revised our server policies: your account is not registered with us so kindly register first using our portal at the link given below."
                PortalLink = "[#00e6e6]Register at [ https://rtv.pl-community.com/panel/ ]"
                DiscordLink = "[#00e6e6]Discord [ https://discord.gg/HFH6sES ]"
                ActivatedBlocked = "[#ffff99][ %s ] has been kicked from the server because their account isn't approved yet."
                ClanBanNotice = "[#e60000]Sorry, Clan [ %s ] have been banned on this server."
                ClanBanNotice2 = "[#e60000]Remove [ %s ] clan tag if you wish to play here."

                /* Used for all commands*/
                TargetXOnline = "[#e68a00]Target is not online"
                CmdError = "%s"
                ErrCmd = "[#e68a00]Unknown command, use /cmds to view available commands."
                NotSpawned = "[#e68a00]You must spawned to use this command."
                FeatureDisabled = "[#e68a00]This feature has been disabled by administrator."

                /* scripts/Commands/Player.nut */             
                OwnStats = "[#00e64d]Your stats: "
                OwnStats1 = "[#00e64d]Kills [ %d ] Deaths [ %d ] K/D Ratio [ %.2f ] Top Spree [ %d ]"
                OwnStats2 = "[#00e64d]Rounds played [ %d ] Wins as: [Attacker: %d Defender: %d] MVP [ %d ] Vehicles Robbed [ %d ]"
                TargetStats = "Stats of [ %s ]"
                Changepass = "[#00e64d]Sucessfully changed password."
                ChangepassOldSameNew = "[#e68a00]New password cannot be same as old password."
                ChangepassNewPassNotEnough = "[#e68a00]Password length must contain more than 4 characters."
                ChangepassOldPass = "[#e68a00]Wrong old password."
                ChangepassSyntax = "[#e68a00]Syntax, /changepass [old password] [new password]"
				SelfCountry = "[#00e64d]Your country [ %s ]"
				TargetCountry = "%s [#00e64d]country [ %s ]"
				NoAdmins = "[#e68a00]There are no admins online right now, you can still contact us on /discord or /forum."
				Admins = "[#ffea00]Online Admins [ %s ]"
				ShowHPSelf = "[#00e64d]Your total health [ %d ]"
				ShowHP = "%s's [#00e64d]Total health [ %d ]"
                ListRules1 = "[#00e6e6]All these things are disallowed in the server:"    
                ListRules2 = "[#00e6e6]Usage of any third party program to gain advantage over other players, scamming, spamming, racism, advertisement of other servers, death-evade, spawn-kill, impersonation, usage of RPG within a range of 20 metres known as close range rpg, usage of VPN."
                HelpMsg = "RTV Server Introduction:"
                HelpMsg1 = "[#ff3300]Attackers - [#00e6e6]Steal the target vehicle and drive it to the checkpoint visible on the radar or map."
                HelpMsg2 = "[#3366ff]Defenders - [#00e6e6]Protect the target vehicle from being stolen by the attackers until round time is over."
                HelpMsg3 = "[#8c8c8c]Spectator - [#00e6e6]Grab your popcorn and spectate the round using /spec."
                SoundsEnable = "[#00e64d]Sound have been enabled."
                SoundsDisable = "[#00e64d]Sound have been disabled."
                GetPlayers = "[#00e64d]Player online: [ %d ] :: Red [ %d ] Blue [ %d ] Spectators [ %d ]"
                RoundActiveGetPlr = "[#00e64d]Round active: Attacker(%s) [ %d ] Defenders(%s) [ %d ] Spectators [ %d ]"
                OwnWorld = "[#00e64d]Your world is [ %d ]."
                TargetWorld = "[#00e64d][ %s ] is on world [ %d ]."
                OwnLevel = "[#00e64d]Your level is [ %d ][ %s ]."
                TargetLevel = "[#00e64d][ %s ] level is [ %d ][ %s ]."
                ReportAdmin = "[#ffff99][ %s ] has reported [ %s ] for reason [ %s ]."
                ReportSubmit = "[#00e64d]Thanks for reporting, admins have been notified."
                ReportSubmit1 = "[#00e64d]Admin not responding? You can also capture evidence and report at /forum properly."
                CantReportSelf = "[#e68a00]You cannot report yourself."
                ReportSyntax = "[#e68a00]Syntax, /report [player] [reason]"
                MVpChange = "[#00e64d]You changed MVP track to [ %s ]."
                MVPSyntax = "[#e68a00]Syntax, /changemvpsound [id]"
                MVPSyntax1 = "[#e68a00][1] - Dancing, [2] - EZ KATKA, [3] - WOAH, [4] - EZ4ENCE, [5] - Nico Nico Nii, [6] - SA Mission Passed [7] - SOSAT BLYAT, [8] - Flawless Victory, [9] - GJ VCPD, [10] - Vi sitter i Ventrilo och Spelar DotA"
                PlaySoundX = "[#00e64d]You played sound [ %d ]"
                PlaySoundSyntax1 = "[#e68a00]Syntax, /playsound [id]"
                LoginSyntax = "[#e68a00]Syntax, /login [password]"
                DisableMVP = "[#00e64d]You disabled MVP sound. No MVP sound will playing for you after round end."
                EnableMVP = "[#00e64d]You enabled MVP sound. You can hear MVP sound after round end."
                TargetDisStats = "[#e68a00]Target player disabled showing stats."
                TargerDisCountry = "[#e68a00]Target player disabled showing country."
                OwnStats3 = "[#00e64d]Lowest average ping [ %d ] Highest average FPS [ %d ] Lowest average FPS [ %d ] Highest average ping [ %d ]"
                AlreadyLogged = "[#e68a00]You already logged."
                ShowCountryOn = "[#00e64d]Your country now shown on join."
                ShowCountryOff = "[#00e64d]Your country now hidden from public."
                ShowStatsOn = "[#00e64d]Your stats are now public."
                ShowStatsOff = "[#00e64d]Your stats are now hidden from public."
                AllowPMOn = "[#00e64d]You allowed incoming private message."
                AllowPMOff = "[#00e64d]You disallowed incoming private message."
                TargetIgnored = "[#00e64d]You ignored [ %s ]."
                TargetAlreadyIgnore = "[#e68a00]You already ignored target player."
                CantIgnoreSelf = "[#e68a00]You cant ignore yourself."
                TargetUnIgnored = "[#00e64d]You unignored [ %s ]."
                TargetNotIgnore = "[#e68a00]Target player is not ignored by you."
                CantUnIgnoreSelf = "[#e68a00]Music, makes me, hiiiigh"
                IgnoreList = "[#00e64d]Ignore list [ %s ]"
                NoIgnoreList = "[#e68a00]Your ignore list is empty."
                UnignoreInvalidIndex = "[#e68a00]Invalid id, use /ignorelist to view valid id."    
                UnignoreNotNum = "[#e68a00]ID must be in number."
                UnIgnoreSyntax = "[#e68a00]Syntax, /unignore [ID]"
                IgnoreSyntax = "[#e68a00]Syntax, /ignore [ID]"
                CantPMSelf = "[#e68a00]Oh my god its %s from %s, legend!"
                PMSyntax = "[#e68a00]Syntax, /pm [player] [text]"
                OwnerOnline = "[#ffea00]Online owner: [ %s ] Status [ %s ]"
                ManagerOnline = "[#ffea00]Online manager: [ %s ] Status [ %s ]"
                AdminOnline = "[#ffea00]Online admin: [ %s ] Status [ %s ]"
                ModOnline = "[#ffea00]Online moderator: [ %s ] Status [ %s ]"
                DisablePChat = "[#00e64d]You disabled public chat."
                EnablePChat = "[#00e64d]You enabled public chat."
                DisableTaunt = "[#00e64d]You disabled killer taunt message."
                EnableTaunt = "[#00e64d]You enabled killer taunt message."
                DisableTaunt1 = "[#00e64d]You disabled taunt message."
                TauntUpdate = "[#00e64d]Taunt text updated. [ %s ]"
                TauntSyntax = "[#e68a00]Syntax, /taunttext [text/disable]"



                /* scripts/Commands/Misc.nut */             
                ShowFPSPingSelf = "[#00e64d]Your Ping [ %d - Max: %d Min: %d Average: %d ] FPS [ %d - Max: %d Min: %d Average: %d ] Jitter [ %d ]"
                ShowFPSPing = "[#00e64d][ %s ] Ping [ %d - Max: %d Min: %d Average: %d ] FPS [ %d - Max: %d Min: %d Average: %d ] Jitter [ %d ]"
                ShowForum = "https://rtv.pl-community.com"
                ShowDiscord = "https://discord.gg/HjQznwA"
                ShowCreditsHeader = "[#cccc00]RTV 3 Credits"
                ShowCreditsMain = "[#00e64d]Lead Scripter [#ffffff]KingOfVC"
				ShowCreditsDev = "[#00e64d]Scripters [#ffffff]KingOfVC, [MK]SahiL"
                ShowCreditsUI = "[#00e64d]Client UI Sprites [#ffffff]Spiller"
                ShowCreditPanel = "[#00e64d]Web Panel Developers [#ffffff]ELK_PL, KingOfVC"
                ShowCreditsSpecial = "[#00e64d]Scripting Advisors [#ffffff]ELK_PL, Doom_Kill3R, SLC, [VU]Xmair "
                ShowCmds = "[#00e64d]Basic commands (/) help, rules, players, changepass, stats, changepack, base, hp, fps/ping, fpslimit, pinglimit, jitterlimit, report, admins, credits, forum, discord, country, level, base, surrender, changemvpsound, playsound, disablemvp, cum, love, spawnarmour, spawnammo, spawnhp, ignore, unignore, ignorelist, carcol, doodle, showtaunt, taunttext, publicchat "
				ShowKeyBinds = "[#00e64d][F3] toggle chat mode.\n[F4] to toggle autorespawn.\n[F3] toggle show team on screen.\n[B] to change pack."
                ShowCmdAdmin = "[#00e64d]Type /acmds for available admin commands."
                ErrCmdNoLog = "[#e68a00]Please register or login to use/view available commands."
                CmdsSyntax = "[#e68a00]Syntax, /cmds [basic/op]"
                Cum = "[#00e64d][ %s ] has rub his dick and release some cum."
                Cum2 = "[#00e64d][ %s ] shooting cum on [ %s ] face."
                CmdOnCD = "[#e68a00]You need to wait [ %s ] before you can use this command again."
                CumCantShootSelf = "[#e68a00]You cannot shoot yourself."
                Love2 = "[#00e64d][ %s ] loves [ %s ]"
                Love = "[#00e64d][ %s ] needs some love. "


                missleTargetXFound = "[#e68a00]No target found"
                missleTargetTooFar = "[#e68a00]Target is too far"
                missleTargetTooClose = "[#e68a00]Target is too close to you"

                /* scripts/Commands/Gameplay.nut */             
                BaseNotLoad = "[#e68a00]Round has not started yet."
                NotInRound = "[#e68a00]You are not in round."
                BaseInfoHeader = "[#00e64d]Current round: Base [ %s ] Defender [ %s ]"
                BaseInfoStyle2 = "[#00e64d]Author [ %s ] Steal record [ %s (%s) ]"
                PressBCloseMenu = "Use [B] button to open/close weapon pack UI."
                StartSurrender = "[#00e699][ %s ] has starting vote for surrender. Type /surrender if you wish to surrender."
                VoteSurrender = "[#00e699][ %s ] has voted for surrender. [ %d/%d ]"
                SurrenderCantVote = "[#e68a00]Voting currently in progress."
                SurrenderInProgress = "[#e68a00]You cant use this command for now."
                SurrenderNotEnoughVote = "[#00e699]Surrender voting has failed, not enough votes."
                MinePlanted = "[Team Chat] %s[#ffffff]: [#00ffff]I planted mine, they will dancing with coffin guys if they step."
                TooManyMine = "[#e68a00]You or your team has planted too many mines."
                CantSpawnResourceFar = "[#e68a00]You can only spawn resource at your own spawn."
                GetPacks = "[#00e64d]Pack [ %d ] Taken [ %d/%d ]"
                GetPackBrk = "[#00e64d]-------------------------"
                GetPacks1 = "[#00e64d][%s] Pack [ %d ] Taken [ %d/%d ]"

                /* scripts/Commands/Discord.nut */             
                DiscordChat = "%s [#ffffff][Discord]: %s"
				DiscordAdminChat = "%s [#ffffff][Staff Discord]: %s"

                /* scripts/Commands/Admin.nut */
                ErrCmdNoPerm = "[#e68a00]You dont have permission to use this command."

                ExecSucs = "[#00e64d]Code [ %s ] executed."
                ExecErr = "[#e68a00]Execute error [ %s ]"
                ExecSyntax = "[#e68a00]Syntax, /e [code]"
                ClSyntax = "[#e68a00]Syntax, /cl [code]"

                KickSyntax = "[#e68a00]Syntax, /kick [player] [reason]"
                CantKickSelf = "[#e68a00]You cannot kick yourself"
                KickPlayer = "[#ffc266]Admin [ %s ] has kicked [ %s ] from the server. Reason [ %s ]"

                BanSyntax = "[#e68a00]Syntax, /ban [player] [duration] [reason]"
                BanMuteTimeInvalid = "[#e68a00]Duration should be ?m/?h/?d/?w"
                CantBanSelf = "[#e68a00]You cannot ban yourself."
                BanPlayer = "[#ffc266]Admin [ %s ] has banned [ %s ] from the server. Reason [ %s ] Duration [ %s ]"

                MuteSyntax = "[#e68a00]Syntax, /mute [player] [duration] [reason]"
                CantMuteSelf = "[#e68a00]You cannot mute yourself."
                MutePlayer = "[#ffc266]Admin [ %s ] has muted [ %s ]. Reason [ %s ] Duration [ %s ]"

                UnMute = "[#ffc266]Admin [ %s ] has unmuted [ %s ]."
                TargetNotMuted = "[#e68a00]Player is not muted."
                UnMuteSyntax = "[#e68a00]Syntax, /unmute [player]"

                TargetNotSpawn = "[#e68a00]Player is not spawned."
                SpecSynrtax = "[#e68a00]Syntax, /spec [player]"
                SpecNotSpec = "[#e68a00]You must spawn as spectator to use this command."
                CantSpecSelf = "[#e68a00]You cannot spectate yourself."

                NotSpec = "[#e68a00]You are not spectating anyone."

                AdminChat = "[#ffff99]%s: %s"
				ManagerChat = "[#ffff99][MANAGER CHAT] %s: %s"
                AChatSyntax = "[#e68a00]Syntax, /ac [text]"
				MChatSyntax = "[#e68a00]Syntax, /mc [text]"

                ASpecSynrtax = "Syntax, /aspec [player]"

                AEndRound = "[#ffc266]Admin [ %s ] has ended the round."

                ChangeFPSSetting = "[#ffc266]Admin [ %s ] has changed FPS Limit to [ %d ]."
                ChangeFPSSettingSyntax = "Syntax, /fpslimit [value]"
                ChangePingSetting = "[#ffc266]Admin [ %s ] has changed Ping Limit to [ %d ]."
                ChangePingSettingSyntax = "[#e68a00]Syntax, /pinglimit [value]"
                ValueNotNum = "[#e68a00]Value must be in number."
                CurrentFPSLimit = "[#00e64d]Current FPS Limit [ %d ]"
                CurrentPingLimit = "[#00e64d]Current Ping Limit [ %d ]"
                NotPermSetValue = "[#e68a00]You dont have permission to change value."
                FPSLimitBetween = "[#e68a00]FPS limit must between 5 and 60."
                PingLimitBetween = "[#e68a00]Ping limit must between 5 and 10000."
				CurrentAllLimit = "[#00e64d]Current: FPS Limit [ %d ] Ping limit [ %d ] Jitter limit [ %d ]"

				AlertSyntax = "[#e68a00]Syntax, /alert [player] [message]"
				
				RefCmds = "[#00e64d](/) ac ( ' ), end, aspec, [un]freeze, heal, setweather, alert, ann, drown, slap, goto, get, autostart, startbase, changeteam, getbasename"
				ModCmds = "[#00e64d][Moderator] (/) ac ( ' ), end, aspec, [un]mute, [un]freeze, kick, heal, setweather, alert[all], ann[all], drown, slap, goto, get, aduty, teambalancer, autostart, startbase, getip, resetrb, changeteam, getbasename, gotobase, rpgban, unrpgban, getmodule, changeteamname, legacyspawn, comment, gpublicchat, speedtest"
				ACmds = "[#00e64d][Administator] (/) ban, fpslimit, pinglimit, playsoundtoall, healall, setanim, getall, removeacc, resetpass, spawnveh, givewep, setworld, packlimit, reloadbases, readonly"
				MCmds = "[#00e64d][Manager] (/) setpassword, setlevel, setbasename, setattpos, setdefpos, setcppos, settvpos, settvmodel, addbase, delbase"
				DCmds = "[#00e64d][Owner] (/) e, cl"
				
				MapCmds = "[#00e64d]Mapper Commands: (/) setbasename, setattpos, setdefpos, setcppos, settvpos, settvmodel, addbase, delbase"

                LoveLetter = "[#e6e600]You have been warned, due to your wrong behaviour and/or actions."

                WarnExceeded = "[ %s ] has been kicked as their warnings reached the limit. Warning [3/3]"

                ExecSucsAll = "[#ffff99]Admin [ %s ] executed some code."
                SpecMsgAll = "[#ffff99]Admin [ %s ] is now specting [ %s ]."
                SendAlertMsgAll = "[#ffff99]Admin [ %s ] has sent alert with message [ %s ] to [ %s ]."
                SendAlertMsgAll2 = "[#ffff99]Admin [ %s ] has sent alert with message [ %s ] to all players."
                SendAnnMsgAll = "[#ffff99]Admin [ %s ] has sent announcement with message [ %s ] to [ %s ]." 
                SendAnnMsgAll2 = "[#ffff99]Admin [ %s ] has sent announcement with message [ %s ] to all players."
                PlaySoundToAll = "[#ffff99]Admin [ %s ] has played sound ID [ %s ] for all players." 
                HealAll = "[#ffc266]Admin [ %s ] has healed everyone."
                HealPlayer = "[#ffff99]Admin [ %s ] has healed [ %s ]."
                HealBy = "[#e6e600]You have been healed by Admin [ %s ]."
                SetWeather = "[#ffc266]Admin [ %s ] has changed the weather to [ %s ]."
                SetPasswordToServer = "[#ffff99]Admin [ %s ] has set server password to [ %s ]."
                SetPasswordToServerUnlockedReal = "[#ffff99]Admin [ %s ] has unlocked the server." 
                SlapSomeone = "[#ffc266]Admin [ %s ] slapped [ %s ]. Reason [ %s ]"
                DrownPlayer = "[#ffc266]Admin [ %s ] drowned [ %s ]. Reason [ %s ] Warning [%d/3]"
                ReloadScript = "[#ffff99]Admin [ %s ] has reloaded the script."
                SetLevelAdmin = "[#ffff99]Admin [ %s ] has changed [ %s ] level to [ %s ]."
				SetMapAdmin = "[#ffff99]Admin [ %s ] has set [ %s ] as a mapper."
				DelMapAdmin = "[#ffff99]Admin [ %s ] has removed [ %s ] as a mapper."
                AdminPromote = "[#e6e600]You have been promoted to [ %s ]."
                AdminDemoted = "[#e6e600]You have been demoted to [ %s ]."
                SetAnim = "[#ffff99]Admin [ %s ] has set [ %s ] anim to [ %d ]."
                SetAnimVictim = "[#e6e600]Admin [ %s ] has changed your anim."
                GotoPlayer = "[#ffff99]Admin [ %s ] has teleported to [ %s ]."
                GetAll = "[#ffc266]Admin [ %s ] has teleported all players in the server to him."
                GetPlayer = "[#ffff99]Admin [ %s ] is getting [ %s ]."
                SpawnBanAll = "[#ffc266]Admin [ %s ] has spawn banned [ %s ]. Reason [ %s ]"
                UnbanSpawn = "[#ffc266]Admin [ %s ] removed spawn ban of [ %s ]."
                LoveLetter2 = "[#e6e600]You have been spawn banned, due to your wrong behaviour and/or actions."
                SpawnUnbanPlr = "[#e6e600]You have been warned, due to your wrong behaviour and/or actions."
                ChangeNamePlr = "[#e6e600]Admin [ %s ] has changed your name to [ %s ]."
                ChangeNameAdmin = "[#ffff99]Admin [ %s ] transferred account stats of [ %s ] to [ %s ]."
                RemoveAcc = "[#ffc266]Admin [ %s ] has removed account [ %s ]."
                GetOriginIP = "[#00e64d][ %s ] origin IP [ %s ]"
                DisableTBlr = "[#ffc266]Admin [ %s ] has disabled the team balancer."
                EnableTBlr = "[#ffc266]Admin [ %s ] has enabled the team balancer." 
                AdutyOn = "[#ffc266]Admin [ %s ] is on admin duty now."
                AdutyOff = "[#ffc266]Admin [ %s ] is no longer on admin duty."
                EnableAutoStart = "[#ffc266]Admin [ %s ] has enabled autostart." 
                DisableAutoStart = "[#ffc266]Admin [ %s ] has disabled autostart." 
                ManualStartbase = "[#ffc266]Admin [ %s ] has started base [ %s ]."
                StartBaseError = "[#e68a00]Start base error [ %s ]"
                FreezePlr = "[#ffc266]Admin [ %s ] has frozen [ %s ]."
                UnFreezePlr = "[#ffc266]Admin [ %s ] nas unfrozen [ %s ]."
                SpawnVehicle = "[#ffff99]Admin [ %s ] has spawned vehicle [ %s ]."

                AlertAllSyntax = "[#e68a00]Syntax, /alertall [message]"
                AnnSyntax = "[#e68a00]Syntax, /ann [player] [message]"
                AnnAllSyntax = "[#e68a00]Syntax, /annall [message]"
                ErrPlaySound = "[#e68a00]Error on playsound [ %s ]"
                PlaySoundSyntax = "[#e68a00]Syntax, /playsoundtoall [ID]"
                HealPlayerSyntax = "[#e68a00]Syntax, /heal [player]"
                SetWeatherSyntax = "[#e68a00]Syntax, /setweather [ID]"
                ServerAlreadyUnlock = "[#e68a00]Server is already unlocked."
                SlapSyntax = "[#e68a00]Syntax, /slap [player] [reason]"
                CantDrownSelf = "[#e68a00]You cannot drown yourself."
                DrownSyntax = "[#e68a00]Syntax, /drown [player] [reason]"
                CantSetSelfLevel = "[#e68a00]You cannot set your own level."
				CantSetSelfMapper = "[#e68a00]You cannot set your own mapper permissions."
				AlreadyMapper = "[#e68a00]Given player already have mapper permissions."
				AlreadyNotMapper = "[#e68a00]Given player does not have mapper permissions."
                StaffLevelBelow0 = "[#e68a00]Level cannot be lower than 0."
                SetLevelSyntax = "[#e68a00]Syntax, /setlevel [player] [level]"
				SetMapperSyntax = "[#e68a00]Syntax, /setmapper [player]"
				DelMapperSyntax = "[#e68a00]Syntax, /remmapper [player]"
                SetAnimSyntax = "[#e68a00]Syntax, /setanim [player] [anim]"
                GotoSyntax = "[#e68a00]Syntax, /goto [player]"
                CantGotoSelf = "[#e68a00]You cannot goto yourself."
                GetSyntax = "[#e68a00]Syntax, /get [player]"
                SpawnBanSyntax = "[#e68a00]Syntax, /spawnban [player]"
                CantGetSelf = "[#e68a00]You cannot get yourself."
                TargetAlreadySpawnban = "[#e68a00]Target already spawn banned."
                CantSpawnbanSelf = "[#e68a00]You cannot spawnban yourself."
                TargetNotSpawnBanned = "[#e68a00]Target is not spawn banned."
                CantUnbanSpawnSelf = "[#e68a00]You cannot unspawnban yourself."
                UnbanSpawnSyntax = "[#e68a00]Syntax, /unspawnban [player] [reason]"
                NewNameExist = "[#e68a00]New name already exists."
                TransfernickSyntax = "[#e68a00]Syntax, /transfernick [full old nick] [full new nick]"
                OldNameNotExist = "[#e68a00]Old name does not exist."
                TargetOnline = "[#e68a00]Target in the server right now."
                RemNameNotExist = "[#e68a00]Given name does not exist."
                RemAccSyntax = "[#e68a00]Syntax, /removeacc [full name]"
                GetIPSyntax = "[#e68a00]Syntax, /getip [player]"
                RoundActiveErr = "[#e68a00]Round is active."
                AutoStartErr = "[#e68a00]Error on autostart [ %s ]"
                InvalidBaseID = "[#e68a00]Invalid base ID."
                NotEnoughPlr = "[#e68a00]Insufficient players."
                RoundArAct = "[#e68a00]Round is already active."
                AutostartAlreadyEnable = "[#e68a00]Autostart is enabled, please disable it first."
                StartbasrSyntax = "[#e68a00]Syntax, /startbase [ID]"
                TargetAlreadyFreeze = "[#e68a00]Target already freezed."
                CantFreezeSelf = "[#e68a00]You cannot freeze yourself."
                FreezeSyntax = "[#e68a00]Syntax, /freeze [player]"
                TargetNotFreeze = "[#e68a00]Target is not freezed."
                UnFreezeSyntax = "[#e68a00]Syntax, /unfreeze [player]"
                SpawnVehicleErr = "[#e68a00]Vehicle Model ID should be between 130-236, use /infmodelsearch for Model IDs."
                CantSpawnVehInRound = "[#e68a00]You cannot spawn vehicles when round is active."
                SpawnVehSyntax = "[#e68a00]Syntax, /spawnveh [Model ID]"

                ResetRB = "[#ffff99]Admin [ %s ] has reset the base replaying mechanism."
                ResetPassword2 = "[#e6e600]Admin [ %s ] has changed your password to [ %s ]. Please use /changepass after logging in with temporary password."
                ChangePasswordAdmin = "[#ffff99]Admin [ %s ] has changed password of [ %s ]."
                ResetPassSyntax = "[#e68a00]Syntax, /resetpass [full name] [password]"

                ChangeWorldAdmin = "[#ffff99]Admin [ %s ] has changed [ %s ] world to [ %d ]."
                ChangeWorldAdmin = "[#e6e600]Admin [ %s ] has changed your world."
                SetWorldSyntax = "[#e68a00]Syntax, /setworld [player] [world]"

                GiveWeaponAll = "[#ffff99]Admin [ %s ] has given weapon [ %s ] to everyone."
                GiveWeaponAllWithAmmo = "[#ffff99]Admin [ %s ] has given weapon [ %s ] with ammo [ %d ] to everyone." 
                GiveWeaponAmmoError = "[#e68a00]Ammo should be between 0 and 9999 (inclusive)."
                GiveWeaponError = "[#e68a00]Invalid weapon name/id."
                GiveWeaponPlr = "[#ffff99]Admin [ %s ] has given weapon [ %s ] to [ %s ]."
                GiveWeaponPlrWithAmmo = "[#ffff99]Admin [ %s ] has given weapon [ %s ] with ammo [ %d ] to [ %s ]." 
                GiveWepSyntax = "[#e68a00]Syntax, /givewep [player/all] [weapon] [ammo]"

                ChangeteamAdmin = "[#ffc266]Admin [ %s ] has changed [ %s ] team to [ %s ]."
                ChangeTeamPlrAtt = "[#e6e600]Admin [ %s ] has changed your team to attacker."
                TargetAlreadyAtt = "[#e68a00]Target already in team attacker."
                ChangeTeamPlrDef = "[#e6e600]Admin [ %s ] has changed your team to defender."
                TargetAlreadyDef = "[#e68a00]Target already in team defender."
                ChangeTeamPlrSpec = "[#e6e600]Admin [ %s ] has changed your team to spectator."
                RemoveFromRound ="[#e6e600]Admin [ %s ] has removed you from active round." 
                TargetAlreadySpec = "[#e68a00]Target already in team spectator."
                ChangeteamTargetNotGiven = "[#e68a00]Teams can only be att/def/spec."
                ChangeTeamSyntax = "[#e68a00]Syntax, /changeteam [player] [att/def/spec]"

                SpawnObj = "[#ffff99]Admin [ %s ] has spawned object ID [ %d ] on pos [ %s ] angle [ %s ]."
                WrongObjID = "[#e68a00]Object ID is invalid."
                CreateObjSyntax = "[#e68a00]Syntax, /createobj [object id]"

                EnableEventMode = "[#ffc266]Admin [ %s ] has disabled event mode."
                DisableEventMode = "[#ffc266]Admin [ %s ] has enabled event mode."

                SetPackLimitAll = "[#ffff99]Admin [ %s ] has limited pack [ %d ] to [ %d ] per team."
                ViewCurrentPackLimit = "[#00e64d]Pack [ %d ] Limit is [ %d ]."
                PackLimitErr = "[#e68a00]Packs are only available between 1-7."
                SetPackLimitSyntax = "[#e68a00]Syntax, /packlimit [pack] [limit]"

                ChangeDefSpawn = "[#ffff99]Admin [ %s ] changed Defenders Spawnpos for base [ %s ]."
                SetdefPosSyntax = "[#e68a00]Syntax, /setdefpos [base id]"
                
                ChangeAttSpawn = "[#ffff99]Admin [ %s ] changed Attacker Spawnpos for base [ %s ]."
                SetattPosSyntax = "[#e68a00]Syntax, /setattpos [base id]"

                ChangeCPPos = "[#ffff99]Admin [ %s ] changed Checkpoint position for base [ %s ]." 
                SetCPPosSyntax = "[#e68a00]Syntax, /setcppos [base id]"

                ChangeVehiclePos = "[#ffff99]Admin [ %s ] changed Target Vehicle spawn position for base [ %s ]."
                SetTVPosSyntax =  "[#e68a00]Syntax, /settvpos [base id]"

                ChangeBaseName = "[#ffff99]Admin [ %s ] changed base [ %s ] name to [ %s ]."
                SetbasenameSyntax = "[#e68a00]Syntax, /setbasename [base id] [new name]"

                ChangeTVModel = "[#ffff99]Admin [ %s ] changed base [ %s ] target vehicle model to [ %s ]."
                SetTVModelSyntax = "[#e68a00]Syntax, /settvmodel [base id] [model id]"

                GetBaseID = "[#00e64d]Base ID [ %d ] Name [ %s ]"
                GetBaseNameSyntax = "[#e68a00]Syntax, /getbasename [base id]"

                BaseNotFound = "[#e68a00]Base not found."
                SearchBaseSyntax = "[#e68a00]Syntax, /searchbase [base name]"

                SendCrash = "[#ffff99]Admin [ %s ] has crashed [ %s ]."
                CrashSyntax = "[#e68a00]Syntax, /crash [player]"

                AddBase1 = "[#00e64d]Base ID [ %d ] added."
				DelBase = "[#00e64d]Base ID: [ %d ] deleted."
                AddBaseWarn = "[#e68a00][WARNING] Remember to use /setbasename, /setattpos, /setdefpos, /setcppos, /settvpos, /settvmodel for the new base before playing it."
                BaseIDExist = "[#e68a00]Given base ID already exists."
				BaseIDNotExist = "[#e68a00]Given base ID does not exist."
                AddBaseSyntax = "[#e68a00]Syntax, /addbase [ID]"
				DelBaseSyntax = "[#e68a00]Syntax, /delbase [ID]"

                ReloadBase = "[#ffff99]Admin [ %s ] has reloaded all bases from the database."

                TurnOffStealthMode = "[#ffff99]Admin [ %s ] is no longer hiding their admin identity."
                TurnOnStealthMode = "[#ffff99]Admin [ %s ] has hidden their admin identity."

                GotoBase = "[#ffff99]Admin [ %s ] has teleported to base [ %s ]."
                GotobaseSyntax = "[#e68a00]Syntax, /gotobase [base id]"

                RPGBanSyntax = "[#e68a00]Syntax, /rpgban [player] [duration] [reason]"
                CantRPGBanSelf = "[#e68a00]You cannot RPG ban yourself."
                RPGBanPlayer = "[#ffc266]Admin [ %s ] has banned [ %s ] from using set 4. Reason [ %s ] Duration [ %s ]"

                UnRPGBan = "[#ffc266]Admin [ %s ] has unbanned [ %s ] from using set 4."
                TargetNotRPGBan = "[#e68a00]Player is not RPG banned."
                UnRPGBanSyntax = "[#e68a00]Syntax, /unrpgban [player]"

                GetModuleSyntax = "Syntax, /getmodule [player]"
                GetModule = "[#ffff99]Admin [ %s ] is getting [ %s ] module."

                ChangeteamName = "[#ffc266]Admin [ %s ] has changed [ %s ] name to [ %s ]."
                ChangeteamNameWrongTeam = "[#e68a00]Team should be 'red' or 'blue'."
                ChangeteamNameSyntax = "[#e68a00]Syntax, /changeteamname [red/blue] [new team name]"

                ServerOnWriteOnlyMode = "[#e68a00]This command cant be used on read only mode."

                BanMuteTimeInvalid2 = "[#e68a00]Time cannot exceeded 1day."

                GetSpeedtestResult = "[#ffff99][ %s ] ticks per 5000(ms) [ %d ]"
                SpeedtestSyntax = "[#e68a00]Syntax, /speedtest [player]"
                SpeedtestInt = "[#00e64d]Speedtest on [ %s ] begin."

                DisableLegacySpawn = "[#ffc266]Admin [ %s ] has disabled legacy spawn screen."
                EnableLegacySpawn = "[#ffc266]Admin [ %s ] has enabled legacy spawn screen."

                DisableReadOnly = "[#ffc266]Admin [ %s ] has disabled read only mode."
                EnableReadOnly = "[#ffc266]Admin [ %s ] has enabled read only mode."

                ChangeJitterSetting = "[#ffc266]Admin [ %s ] has changed Jitter Limit to [ %d ]."
                JitterLimitBetween = "[#e68a00]Jitter limit must between 5 and 10000."

                RemoveComment = "[#ffff99]Admin [ %s ] has removed [ %s ] comment."
                AddComment = "[#ffff99]Admin [ %s ] has added comment on [ %s ] with [ %s ]."
                CommentSyntax = "[#e68a00]Syntax, /comment [player] [text/clear]"

                DisablePublicChat = "[#ffc266]Admin [ %s ] has disabled public chat."
                EnablePublicChat = "[#ffc266]Admin [ %s ] has enabled public chat."

                /* scripts/Classes/panel.nut */
                SetLevelAdminPanel = "[#ffff99]Admin [ %s ] has changed [ %s ] level to [ %s ] from panel."
                ChangeNamePlrPanel = "[#e6e600]Admin [ %s ] has changed your name to [ %s ] from panel."
                ChangeNameAdminPanel = "[#ffff99]Admin [ %s ] has changed [ %s ] name to [ %s ] from panel."
                ResetPassword2Panel = "[#e6e600]Admin [ %s ] has changed your password to [ %s ] from panel. Please use /changepass after logged with temporary password."
                ChangePasswordAdminPanel = "[#ffff99]Admin [ %s ] has changed [ %s ] password from panel."
                BanPlayerPanel = "[#ffc266]Admin [ %s ] has panel-banned [ %s ] from the server. Reason [ %s ] Duration [ %s ]"
                UnBanPlayerPanel = "[#ffc266]Admin [ %s ] has unbanned [ %s ] from panel."
                RPGBanPlayerPanel = "[#ffc266]Admin [ %s ] has panel-banned [ %s ] from using set 4. Reason [ %s ] Duration [ %s ]"
                UnRPGBanPlayerPanel = "[#ffc266]Admin [ %s ] has panel-unbanned [ %s ] from using set 4."
                MutePlayerPanel = "[#ffc266]Admin [ %s ] has muted [ %s ] from panel. Reason [ %s ] Duration [ %s ]"
                UnMutePanel = "[#ffc266]Admin [ %s ] has unmuted [ %s ] from panel."
	
				/* scripts/Classes/discord.nut */
				DiscordExecSucs = "Discord Admin [ %s ] executed some code."
				DiscRemoveAcc = "Discord Admin [ %s ] has removed account [ %s ]."
				DiscLockServer = "Discord Admin [ %s ] has set server password to [ %s ]."
				DiscUnlockServer = "Discord Admin [ %s ] unlocked the server."
				DiscSW = "Discord Admin [ %s ] has changed the weather to [ %s ]."

                /* Operations */
                OperationMissionComplete = "[#00cccc]You completed mission [ %s ] and got [ +%d ] points."
                OperationWeek = "[#00cccc]Missions for week %d:"
                OperationMissionDes = "[#00cccc]Mission [ %s ] Points [ %d ] Progress [ %s ]"
                OperationScore = "[#00cccc]Your operation level [ %d ] Score required for next level [ %d/%d ]"
                OperationIntro = "[#00cccc]'Operation Banshee' week 5 and 6 missions are now available! Use /missions to check available mission. You can use /opscore to view your operation level and reward."
                OperationMissionDailyReward = "[#00cccc]You get [ +50 ] points as daily login reward."
                DoodleSyntax = "[#e68a00]Syntax, /doodle [text]"
                DoodleScs = "[#00e64d]Doodle updated."
                OperationCommandLevelNotEnough = "[#e68a00]You need have at least Operation Level %d or above to use this command."
                OperationReward = "[#00e64d]Reward [ %s ]"
                OperationLevelUp = "[#00cccc]You have been level up to [ %d ]!" 
                OperationRewardUnlock = "[#00cccc]You unlocked reward [ %s ]"
                MissionSyntax = "[#e68a00]Syntax, /missions [1/2/3/4/5/6]"
                CarcolUpdated = "[#00e64d]Custom vehicle color has been updated. Vehicle color will change when you enter."
                CarcolNotNum = "[#e68a00]Vehicle color value must be in number."
                CarcolSyntax = "[#e68a00]Syntax, /carcol [primary color] [secondary color]"
                ShowOperationCmds = "[#00e64d]Operation related commands (/) missions, opscore, doodle, carcol, spawnhp, spawnarmour, spawnammo"
                TeamSpawnPickupHealth = "[Team Chat] %s[#ffffff]: [#00ffff]I spawned health pickup."
                PickupHealthOnCooldown = "[#e68a00]You need to wait [ %s ] before you can spawn another health pickup."
                PickupHealthAlreadyExist = "[#e68a00]Health pickup already spawned by you or your teammate."
                HealthPickupPicked = "[#e6e600]You have recieved [ +%d ] HP."
                HealthPickupCantTakeLowerThan40 = "[#e68a00]You cannot pick this when you have 50 HP or above."
                TeamSpawnPickupArmour = "[Team Chat] %s[#ffffff]: [#00ffff]I spawned armour pickup."
                PickupArmourOnCooldown = "[#e68a00]You need to wait [ %s ] before you can spawn another armour pickup."
                PickupArmourAlreadyExist = "[#e68a00]Armour pickup already spawned by you or your teammate."
                ArmourPickupPicked = "[#e6e600]You got [ +%d ] Armour."
                ArmourPickupCantTakeLowerThan50 = "[#e68a00]You cannot pick this when you have 50 Armour or above."
                OperationIntro1 = "[#ff9900][Rob The Vehicle Championship] Register yourself or your team at [ rtv.pl-community.com ]"
                TeamSpawnPickupAmmo = "[Team Chat] %s[#ffffff]: [#00ffff]I spawned ammo pickup."
                PickupAmmoOnCooldown = "[#e68a00]You need to wait [ %s ] before you can spawn another ammo pickup."
                PickupAmmoAlreadyExist = "[#e68a00]Ammo pickup already spawned by you or your teammate."
                AmmoPickupPicked = "[#e6e600]You weapon ammo have been refilled."
                AmmoPickupCantTake = "[#e68a00]You cannot use this pickup because your weapon set does not include weapon with limited ammo."
                OperationWeek1 = "[#00cccc]Missions for week 5 and 6:"


                /* Radio Chat */
                TeamChatEnteringVeh = "[Team Chat] %s[#ffffff]: [#00ffff]I am entering the target vehicle."
                TeamChatBackup = "[Team Chat] %s[#ffffff]: [#00ffff]I need backup!"
                TeamChatClearArea = "[Team Chat] %s[#ffffff]: [#00ffff]Clear the area!"
                TeamChatRush = "[Team Chat] %s[#ffffff]: [#00ffff]Rush them!"
                TeamChatFallBack = "[Team Chat] %s[#ffffff]: [#00ffff]Fall back!"
                TeamChatAgree = "[Team Chat] %s[#ffffff]: [#00ffff]Agree."
                TeamChatDisagree = "[Team Chat] %s[#ffffff]: [#00ffff]No."
                TeamChatEnemySpotted = "[Team Chat] %s[#ffffff]: [#00ffff]I have spotted an enemy."
                TeamChatCamp = "[Team Chat] %s[#ffffff]: [#00ffff]I am going to camp their spawn."

                /* scripts/Commands/Mapping.nut */
                CurrentInEditMode = "[#e68a00]You currently editing something."
                NotInAdminDuty = "[#e68a00]You must be in admin duty to use this command."

                ObjAdded = "[#00e64d]Object added. ID [ %d ]"
                ObjCreateErr = "[#e68a00]An error occured while adding object. [ %d ]"
                ModelNotNum = "[#e68a00]Object model must be in number."
                AddObjectSyntax = "[#e68a00]Syntax, /addobject [model]"

                EditingObject = "[#00e64d]You additing object. Model [ %d ] ID [ %d ]"
                SomeoneEditing = "[#e68a00][ %s ] is editing this object."
                ObjectIDNotFound = "[#e68a00]Object ID not found."
                ModelIDNotNum = "[#e68a00]Object ID must be in number."
                EditObjectSyntax = "[#e68a00]Syntax, /editobject [ID]"

                ObjNearestFound = "[#00e64d]Object found: [ %s ]"
                ObjNotFound = "[#e68a00]No object found."
                RadiusNotFloat = "[#e68a00]Radius must be in float or integer."
                FindObjSyntax = "[#e68a00]Syntax, /findobject [radius]"

                /* scripts/Classes/object.nut */
                ObjSave = "[#00e64d]Object saved."
                ObjDeleted = "[#00e64d]Object deleted."
                ObjClone = "[#00e64d]Object cloned. ID [ %d ]"
                ObjCloneErr = "[#e68a00]An error occured while cloning object. [ %s ]"
                EditTypeSwitch = "[#00e64d]You switched edit mode to [ %s ]"

    }
}
